In [1]:
import numpy as np

1) Создать вектор размера 10, заполненный нулями.

In [2]:
z = np.zeros(10)
print z

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


2) Создать вектор размера 10, заполненный единицами. 

In [3]:
z = np.ones(10)
print z

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


3) Создать вектор размера 10, заполненный числом 2.5.

In [4]:
z = np.full(10, 2.5)
print z

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


4) Получить информацию о функции np.add.

In [5]:
?np.add
#or
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


5) Создать вектор со значениями от 10 до 49.

In [27]:
z = np.arange(10, 50)
print z

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


6) Развернуть вектор.

In [28]:
z = z[::-1]

In [29]:
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])