# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [17]:
from sklearn import model_selection, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [18]:
iris = datasets.load_iris()

In [19]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [20]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [21]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [23]:
print('Обучающая выборка:\n', train_data[:5], '\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[ 5.1  3.4  1.5  0.2]
 [ 5.8  2.7  5.1  1.9]
 [ 5.1  3.3  1.7  0.5]
 [ 4.6  3.4  1.4  0.3]
 [ 6.3  2.7  4.9  1.8]] 

Тестовая выборка:
 [[ 5.5  2.3  4.   1.3]
 [ 6.1  3.   4.6  1.4]
 [ 5.4  3.9  1.3  0.4]
 [ 4.9  2.5  4.5  1.7]
 [ 6.   2.7  5.1  1.6]]


In [24]:
print('Метки классов на обучающей выборке:\n', train_labels)
print('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [0 2 0 0 2 2 0 1 2 2 1 2 2 1 0 0 1 1 2 1 0 2 2 1 0 0 1 1 0 0 2 0 1 1 0 0 2
 0 1 2 2 1 1 2 2 0 2 1 2 1 1 1 2 2 2 0 0 2 1 0 1 0 0 0 0 2 1 1 2 1 2 1 2 1
 2 2 1 1 0 0 0 2 2 1 1 2 2 1 2 2 0 0 0 0 0 2 1 0 1 2 1 1 1 2 2]
Метки классов на тестовой выборке:
 [1 1 0 2 1 1 0 1 0 0 2 0 0 1 2 2 2 0 0 2 0 1 2 0 0 2 0 1 2 1 1 2 0 1 1 2 0
 0 1 0 0 1 2 0 1]


### Стратегии проведения кросс-валидации

#### KFold

In [26]:
for train_indices, test_indices in model_selection.KFold(5):
    print(train_indices, test_indices)

TypeError: 'KFold' object is not iterable

In [32]:
for train_indices, test_indices in model_selection.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

[0 1 2 5 9] [3 4 6 7 8]
[3 4 6 7 8] [0 1 2 5 9]


In [33]:
for train_indices, test_indices in model_selection.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [28]:
target = np.array([0] * 5 + [1] * 5)
print(target)
for train_indices, test_indices in model_selection.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]


TypeError: __init__() got an unexpected keyword argument 'n_folds'

In [29]:
target = np.array([0, 1] * 5)
print(target)
for train_indices, test_indices in model_selection.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]


TypeError: __init__() got an unexpected keyword argument 'n_folds'

#### ShuffleSplit

In [36]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

[2 9 8 4 7 6 5 1] [3 0]
[3 2 1 5 0 9 6 4] [8 7]
[0 2 3 4 9 1 7 5] [8 6]
[9 2 3 5 1 0 7 4] [6 8]
[9 5 1 6 8 4 2 3] [0 7]
[5 4 8 6 9 7 0 1] [2 3]
[4 6 5 3 8 9 2 1] [7 0]
[4 9 6 8 5 0 7 2] [3 1]
[8 2 7 4 6 1 5 3] [0 9]
[7 6 2 5 0 8 9 1] [3 4]


#### StratifiedShuffleSplit

In [37]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[5 7 0 1 2 6 4 8] [3 9]
[9 3 4 2 5 1 8 7] [6 0]
[4 2 8 1 0 7 9 6] [3 5]
[6 3 5 0 2 1 7 9] [4 8]


#### Leave-One-Out

In [38]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators